// Generated by dts-bundle v0.7.3

declare module 'ruta' {
    export { Json } from 'ruta/Json';
    export { JsonConvert } from 'ruta/JsonConvert';
    export { Serializable } from 'ruta/Serializable';
    export { JsonSettings } from 'ruta/JsonSettings';
}

declare module 'ruta/Json' {
    import { IJsonConverter } from 'ruta/IJsonConverter';
    export namespace Json {
        function ignore(): (target: any, propertyKey: any, descriptor?: any) => any;
        function name(name: any): (target: any, propertyKey: any, descriptor?: any) => any;
        function type(Ctor: any, options?: any): (target: any, propertyKey: any, descriptor?: any) => any;
        function converter(Converter: Partial<IJsonConverter>): (target: any, propertyKey: any, descriptor?: any) => any;
        function stringify(): (target: any, propertyKey: any, descriptor?: any) => any;
    }
}

declare module 'ruta/JsonConvert' {
    import { JsonSettings } from 'ruta/JsonSettings';
    import { IJsonConverter } from 'ruta/IJsonConverter';
    export namespace JsonConvert {
        function toJson(model: any, settings?: JsonSettings): any;
        function fromJson<T>(json: any, Ctor: new (...args: any[]) => T, settings?: JsonSettings): any;
    }
    export const JsonConverters: IJsonConverter[];
}

declare module 'ruta/Serializable' {
    import { JsonSettings } from 'ruta/JsonSettings';
    export class Serializable<T> {
        constructor(partial?: Partial<T>);
        static fromJson(json: any, settings?: JsonSettings): any;
        toJson(settings?: JsonSettings): any;
    }
}

declare module 'ruta/JsonSettings' {
    export interface JsonSettings {
        propertyResolver?: 'camelCase' | 'underScore';
    }
}

declare module 'ruta/IJsonConverter' {
    import { JsonSettings } from 'ruta/JsonSettings';
    import { PropertyInfo } from "ruta/PropertyInfo";
    export interface IJsonConverter {
        supports(val: any, type?: Function): boolean;
        fromJson(jsonValue: any, info?: PropertyInfo, settings?: JsonSettings): any;
        toJson(instanceValue: any, info?: PropertyInfo, settings?: JsonSettings): any;
    }
}

declare module 'ruta/PropertyInfo' {
    import { IJsonConverter } from 'ruta/IJsonConverter';
    export interface PropertyInfo {
        property?: string;
        jsonIgnore?: boolean;
        jsonName?: string;
        Type?: Function;
        ArrayType?: Function;
        MapType?: Function;
        Converter?: Partial<IJsonConverter>;
        options?: any;
    }
}

